// Copies contract ABIs from contracts/out into app/src/abi/<Name>.ts (typed `as const` for viem/wagmi).
// Run after `forge build`:  node scripts/export-abis.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");
const dest = join(root, "app", "src", "abi");
mkdirSync(dest, { recursive: true });

const contracts = {
  VolIndex: "VolIndex.sol/VolIndex.json",
  PriceSampler: "PriceSampler.sol/PriceSampler.json",
  MarketClock: "MarketClock.sol/MarketClock.json",
  FuturesMarket: "FuturesMarket.sol/FuturesMarket.json",
  VAMM: "vAMM.sol/VAMM.json",
  MarginAccount: "MarginAccount.sol/MarginAccount.json",
  LPVault: "LPVault.sol/LPVault.json",
  InsuranceFund: "InsuranceFund.sol/InsuranceFund.json",
  FeeCollector: "FeeCollector.sol/FeeCollector.json",
  ProjectTokenHooks: "ProjectTokenHooks.sol/ProjectTokenHooks.json",
  Liquidator: "Liquidator.sol/Liquidator.json",
  VarianceSwap: "VarianceSwap.sol/VarianceSwap.json",
  ComplianceRegistry: "ComplianceRegistry.sol/ComplianceRegistry.json",
  ERC20: "ERC20.sol/ERC20.json",
};

const index = [];
for (const [name, rel] of Object.entries(contracts)) {
  const artifact = JSON.parse(readFileSync(join(out, rel), "utf8"));
  const body = `// Generated by scripts/export-abis.mjs — do not edit.\nexport const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(dest, `${name}.ts`), body);
  index.push(`export { ${name}Abi } from "./${name}";`);
}
writeFileSync(join(dest, "index.ts"), index.join("\n") + "\n");
console.log(`exported ${index.length} ABIs to app/src/abi`);
